default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials.send(Rails.env)[:database][:host] %>
  username: <%= Rails.application.credentials.send(Rails.env)[:database][:username] %>
  password: <%= Rails.application.credentials.send(Rails.env)[:database][:password] %>
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
